url: "https://yunlintang.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/DSC180B-Blog" # the subpath of your site, e.g. /blog
title: "COVID-19 Sentiment Analysis" # the name of your site, e.g. ACME Corp.

# Set the source folder
source: .
destination: _site